#!/bin/bash

if [ -z "$USERNAME" ]; then
    # Request Github username from human
    read -p "Please tell me your Github username:  " USERNAME
    echo
fi

# Github credentials
GTOKEN=""
if [ -e ./.github_token ]; then
    # Obtain the token, which is located in the first line of the file
    GTOKEN=$(head -n 1 .github_token)
else
    # Read in the Token directly from the user
    read -s -p "Personal Github Token:  " GTOKEN
    echo
fi
# Because humans are slow, so we have to wait for them to process the information
sleep 1

# Inform the human that we need a JWT to continue
echo "A valid JWT is required to continue."
echo "Logging in should yield you a token."
echo
sleep 1
# Obtain JWT from human
read -p "Please tell me your Screwdriver JWT:  " JWT
echo "You gave me the token: $JWT"
sleep 1

# execute functional tests
USERNAME="$USERNAME" JWT="$JWT" GTOKEN="$GTOKEN" npm run functional $@
