workflow:
    - publish
    - beta
    - prod

shared:
    image: node:6

jobs:
    main:
        steps:
            - newstep1: echo PR OPEN
            - newstep2: echo PR SYNC
            - newstep3: echo PR BANANA
        secrets:
            # Uploading coverage information to coveralls
            - COVERALLS_REPO_TOKEN

    publish:
        steps:
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - install-ci: npm install npm-auto-version
            - publish-npm: ./ci/publish.sh
            - publish-docker: ./ci/docker.sh
        environment:
            DOCKER_REPO: screwdrivercd/screwdriver
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GIT_KEY
            # Trigger a Docker Hub build
            - DOCKER_TRIGGER

    # Deploy to our beta environment and run tests
    beta:
        steps:
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - wait-docker: DOCKER_TAG=`git describe --abbrev=0 --tags` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`git describe --abbrev=0 --tags` ./ci/k8s-deploy.sh
            - test: npm install && npm run functional
        environment:
            DOCKER_REPO: screwdrivercd/screwdriver
            K8S_CONTAINER: screwdriver-api
            K8S_IMAGE: screwdrivercd/screwdriver
            K8S_HOST: api.k8s.screwdriver.cd
            K8S_DEPLOYMENT: sdapi-beta
            SD_API: beta.api.screwdriver.cd
        secrets:
            # Access key for functional tests
            - ACCESS_KEY
            # Git access token
            - GIT_TOKEN
            # Talking to Kubernetes
            - K8S_TOKEN


    # Deploy to our prod environment and run tests
    prod:
        steps:
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - wait-docker: DOCKER_TAG=`git describe --abbrev=0 --tags` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`git describe --abbrev=0 --tags` ./ci/k8s-deploy.sh
            - test: npm install && npm run functional
        environment:
            DOCKER_REPO: screwdrivercd/screwdriver
            K8S_CONTAINER: screwdriver-api
            K8S_IMAGE: screwdrivercd/screwdriver
            K8S_HOST: api.k8s.screwdriver.cd
            K8S_DEPLOYMENT: sdapi
            SD_API: api.screwdriver.cd
        secrets:
            # Access key for functional tests
            - ACCESS_KEY
            # Git access token
            - GIT_TOKEN
            # Talking to Kubernetes
            - K8S_TOKEN
