cache:
  event: [ $SD_SOURCE_DIR/node_modules ]

shared:
    environment:
        DOCKER_REPO: screwdrivercd/screwdriver
        DOCKER_MULTI_PLATFORM_BUILDS_ENABLED: 1
    annotations:
        beta_config: &beta_config
            image: node:18
            environment:
                K8S_CONTAINER: screwdriver-api
                K8S_IMAGE: screwdrivercd/screwdriver
                K8S_HOST: kubernetes.default.svc
                K8S_DEPLOYMENT: sdapi-beta
                SD_API_HOST: beta.api.screwdriver.cd
                K8S_ENV_KEY: DATASTORE_DYNAMODB_PREFIX
                K8S_ENV_VALUE: beta_rc2_
                TEST_USERNAME: sd-buildbot-functional
                TEST_ORG: screwdriver-cd-test
            secrets:
                # Access key for functional tests
                - SD_API_TOKEN_BETA
                # Git access token
                - GIT_TOKEN_BETA
                # Talking to Kubernetes
                - K8S_TOKEN
        prod_config: &prod_config
            image: node:18
            environment:
                K8S_CONTAINER: screwdriver-api
                K8S_IMAGE: screwdrivercd/screwdriver
                K8S_HOST: kubernetes.default.svc
                K8S_DEPLOYMENT: sdapi
                SD_API_HOST: api.screwdriver.cd
                K8S_ENV_KEY: DATASTORE_DYNAMODB_PREFIX
                K8S_ENV_VALUE: rc2_
                TEST_USERNAME: sd-buildbot-functional
                TEST_ORG: screwdriver-cd-test
            secrets:
                # Access key for functional tests
                - SD_API_TOKEN_PROD
                # Git access token
                - GIT_TOKEN_PROD
                # Talking to Kubernetes
                - K8S_TOKEN

jobs:
    main:
        image: node:18
        annotations:
            screwdriver.cd/ram: TURBO
            screwdriver.cd/cpu: TURBO
        requires:
            - ~pr
            - ~commit
            - ~sd@73:publish #artifact-bookend https://cd.screwdriver.cd/pipelines/73
            - ~sd@9:publish  #models https://cd.screwdriver.cd/pipelines/9
            - ~sd@529:publish  #workflow-parser https://cd.screwdriver.cd/pipelines/529
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - install: npm install
            - duplicate: NPM_FILTER=screwdriver- ./ci/npm-dups.sh
            - test: npm test
            - teardown-coverage: ./ci/coverage.sh
            - teardown-cp-coverage-to-artifacts: cp -rf artifacts/coverage $SD_ARTIFACTS_DIR
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=lib,plugins -Dsonar.tests=test -Dsonar.javascript.lcov.reportPaths=artifacts/coverage/lcov.info -Dsonar.testExecutionReportPaths=artifacts/report/test.xml"
            NODE_OPTIONS: "--max_old_space_size=4096"
        secrets:
            # Uploading coverage information to coveralls
            - COVERALLS_REPO_TOKEN

    publish:
        requires: [main]
        image: node:18
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - install-ci: npm install npm-auto-version
            - publish-npm-and-git-tag: ./ci/publish.sh
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GIT_KEY
    
    docker-publish:
        annotations:
            screwdriver.cd/dockerEnabled: true
            screwdriver.cd/dockerCpu: HIGH
            screwdriver.cd/dockerRam: HIGH
        requires: publish
        template: sd/dind@2.0.20
    
    # Deploy to our beta environment and run tests
    beta:
        requires: [docker-publish]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - wait-docker: DOCKER_TAG=`meta get docker_tag` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`meta get docker_tag` ./ci/k8s-deploy.sh
        <<: *beta_config
    
    beta-part1-test:
        requires: [beta]
        steps:
            - test: |
                npm install
                GIT_TOKEN=${GIT_TOKEN_BETA} SD_API_TOKEN=${SD_API_TOKEN_BETA} npm run functional-beta-part1
        <<: *beta_config
    
    beta-part2-test:
        requires: [beta-part1-test]
        steps:
            - pause: sleep 120
            - test: |
                npm install
                GIT_TOKEN=${GIT_TOKEN_BETA} SD_API_TOKEN=${SD_API_TOKEN_BETA} npm run functional-beta-part2
        <<: *beta_config    

    # Deploy to our prod environment and run tests
    prod:
        requires: [beta-workflow-test]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - wait-docker: DOCKER_TAG=`meta get docker_tag` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`meta get docker_tag` ./ci/k8s-deploy.sh
            - test: |
                npm install
                GIT_TOKEN=${GIT_TOKEN_PROD} SD_API_TOKEN=${SD_API_TOKEN_PROD} npm run functional
        <<: *prod_config