@startuml sd-zip-artifacts-overview

skinparam sequenceMessageAlign center

participant "sd build" as build
participant "store" as store
database "s3(Object Storage)" as s3
participant "api" as api
participant "queue-service" as qservice
queue "Resque(Redis)" as resque
participant "unzip worker" as worker


build -> store: store-cli\nPUT /builds/{id}/ARTIFACTS/SD_ARTIFACT.zip
store -> s3: upload zip artifact
build -> api: POST /builds/{id}/artifacts/unzip
api -> qservice: POST /queue/message?type=unzip
qservice -> resque: enqueue
qservice --> api: response\n(POST /queue/message?type=unzip)
api --> build: response\n(POST /builds/{id}/artifacts/unzip)
worker -> resque : dequeue
worker -> store: GET /builds/{id}/ARTIFACTS/SD_ARTIFACT.zip
store -> s3: download zip artifact
store --> worker: response\n(GET /builds/{id}/ARTIFACTS/SD_ARTIFACT.zip)
worker -> store: PUT /builds/{id}/ARTIFACTS/*
store -> s3: upload unzip artifacts
store --> worker: response\n(PUT /builds/{id}/ARTIFACTS/*)
worker -> store: DELETE /builds/{id}/ARTIFACTS/SD_ARTIFACT.zip
store -> s3: delete zip artifact
store --> worker: response\n(DELETE /builds/{id}/ARTIFACTS/SD_ARTIFACT.zip)

@enduml
