#!/bin/bash -e

if [ -z "$GIT_TOKEN" ] || [ -z "$NPM_TOKEN" ] || [ -z "$DOCKER_TRIGGER" ]; then
  echo Skipping publish in Pull Request
  exit 0
fi

echo Setting up secrets
git remote set-url --push origin https://${GIT_TOKEN}@github.com/screwdriver-cd/screwdriver
npm config set access public > /dev/null 2>&1
npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN} > /dev/null 2>&1

echo Bump the version
./node_modules/.bin/npm-auto-version

echo Publish the package
npm publish

echo Push the new tag to GitHub
git push origin --tags -q

echo Trigger Docker builds
GIT_TAG=`git describe --abbrev=0 --tags`
DOCKER_URL=https://registry.hub.docker.com/u/screwdrivercd/screwdriver/trigger/${DOCKER_TRIGGER}/
# Latest
curl -H "Content-Type: application/json" --data '{"docker_tag": "master"}' -X POST $DOCKER_URL
# Recent Tag
curl -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"${GIT_TAG}\"}" -X POST $DOCKER_URL
